// config/demo.ts
// Showcase fallback mode. sampleBlueprint is a FROZEN SNAPSHOT, generated by
// running the real pipeline once (see scripts/generate-demo-blueprint.ts) —
// not computed live. It must stay this way: the real pipeline depends on
// Prisma, which cannot run inside a browser bundle, and this file is
// imported by client components (JourneyProvider, reveal/blueprint/timeline
// pages) as their offline fallback. If the database or network is ever
// unreachable, this file must still work — so it cannot depend on either.
//
// To regenerate after a meaningful change to lodge data or scoring logic:
//   npx tsx scripts/generate-demo-blueprint.ts

import type { JourneyBlueprint } from "@/types/journey";
import demoBlueprintData from "./demo-blueprint.json";

export { sampleAnswers } from "@/config/sampleAnswers";

export const sampleBlueprint: JourneyBlueprint = demoBlueprintData as JourneyBlueprint;